Module3 task1
htmlacademy-react/132653-what-to-watch-5 pull request #5
Opened 2020-10-13 17:43 UTC by aalexceenko

2020-10-18 09:45 UTC, Shv-sergey70 requested changes

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleSubmit(evt) {
А где этот метод используется?

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleTextChange(evt) {
Метод можно объявить приватным `_handleTextChange`

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleStarClick(checked, index) {
Метод можно объявить приватным

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleTextChange(evt) {
Можно сразу так:
```
  handleTextChange(evt) {
    this.setState({
      textReview: evt.target.value,
    });
  }
```

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +    const newRatingStarsCheked = Array(5).fill(false);
`newRatingStarsCheked` - опечатка

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +    const ratingStarsChecked = this.state.ratingStarsChecked;
Используй деструктуризацию. Не присваивание:
```
const {ratingStarsChecked} = this.state;
```

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +              <textarea className="add-review__textarea" name="review-text" id="review-text" placeholder="Review text"
Стоит сделать все элементы формы управляемыми:
https://ru.reactjs.org/docs/forms.html
То есть значение должно подставляться из стейта

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +      ratingStarsChecked: [false, false, false, false, false],
Думаю достаточно хранить рейтинг как число от 1 до 5. В массиве нет надобности

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/app/app.jsx
>          <Route exact path="/login">
Все пути имеет смысл вынести в перечисление

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/film-card/film-card.jsx
> +  const {film, onFilmCardClick} = props;
Деструктурируй пропсы сразу в параметре

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/components/film-card/film-card.jsx
> +  film: PropTypes.shape({
Структура propTypes для фильма описывается здесь и в `app`. То есть код дублируется. Нужно вынести propTypes для фильма в отдельный файл и уже из него просто импортировать propTypes и вставлять тут и в app

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/mocks/films.js
> +};
Можно сразу так:
```
const generateFilm = () => ({
  id: generateId(),
  title: getRandomArrayItem(TITLES),
  genre: getRandomArrayItem(GENRES),
  previewImage: getRandomArrayItem(POSTER),
  previewVideo: PREVIEW_VIDEO,
  year: getRandomInteger(1900, 2000),
  description: getRandomArrayItems(DESCRIPTION_STRINGS),
  rating: getRandomFloat(0, 10),
  ratingText: getRandomArrayItem(RATING_TEXT),
  votes: getRandomInteger(0, 500),
  director: getRandomArrayItem(NAMES),
  actors: getRandomArrayItems(NAMES),
  runtime: getRandomInteger(5, 180),
  myList: Boolean(getRandomInteger(0, 1)),
});
```

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/mocks/films.js
> +const generateReview = () => {
Здесь тоже можно использовать короткий синтаксис без `return`

2020-10-18 09:45 UTC, Shv-sergey70 commented on src/mocks/films.js
> +    runtime: getRandomInteger(5, 180),
Все цифры нужно вынести в константы или перечисления

2020-10-18 19:06 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleSubmit(evt) {
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/34a59949822b7db5970d61b88958400a79c2b52d)

2020-10-18 19:07 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleTextChange(evt) {
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/34a59949822b7db5970d61b88958400a79c2b52d)

2020-10-18 19:07 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +  handleStarClick(checked, index) {
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/34a59949822b7db5970d61b88958400a79c2b52d)

2020-10-18 19:07 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +    const ratingStarsChecked = this.state.ratingStarsChecked;
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/34a59949822b7db5970d61b88958400a79c2b52d)

2020-10-18 19:08 UTC, aalexceenko commented on src/mocks/films.js
> +};
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/ad011f72f8d776a48002497532981d9ba34c8aa2)

2020-10-18 19:08 UTC, aalexceenko commented on src/mocks/films.js
> +const generateReview = () => {
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/ad011f72f8d776a48002497532981d9ba34c8aa2)

2020-10-18 19:08 UTC, aalexceenko commented on src/mocks/films.js
> +    runtime: getRandomInteger(5, 180),
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/ad011f72f8d776a48002497532981d9ba34c8aa2)

2020-10-18 19:17 UTC, aalexceenko commented on src/components/film-card/film-card.jsx
> +  const {film, onFilmCardClick} = props;
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/fd6076432dea51dd71547cf285eea35a1570ec4c)

2020-10-18 19:17 UTC, aalexceenko commented on src/components/film-card/film-card.jsx
> +  film: PropTypes.shape({
[исправила](https://github.com/aalexceenko/132653-what-to-watch-5/commit/fd6076432dea51dd71547cf285eea35a1570ec4c)

2020-10-19 09:13 UTC, Shv-sergey70 commented on src/mocks/films.js
> +const POSTER = [
`POSTERS`

2020-10-19 09:13 UTC, Shv-sergey70 commented on src/components/add-review-screen/add-review-screen.jsx
> +  films: PropTypes.arrayOf(PropTypes.shape({
Проп-тайпсы для фильма уже описаны в отдельном файле

2020-10-19 20:14 UTC, aalexceenko commented on src/mocks/films.js
> +const POSTER = [
[исправила](https://github.com/htmlacademy-react/132653-what-to-watch-5/pull/5/commits/29879b5b9c45e05e4625540808a3cf10cb39ee9e)

2020-10-19 20:15 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +  films: PropTypes.arrayOf(PropTypes.shape({
[исправила](https://github.com/htmlacademy-react/132653-what-to-watch-5/pull/5/commits/e3e08287ad97d3595f83335cfa9a9a1d810b62df)

2020-10-19 20:15 UTC, aalexceenko commented on src/components/app/app.jsx
>          <Route exact path="/login">
[исправила](https://github.com/htmlacademy-react/132653-what-to-watch-5/pull/5/commits/ac9f8d29b9ef22be0af3c4b4de5c237b0ad9d289)

2020-10-19 20:15 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +      ratingStarsChecked: [false, false, false, false, false],
[исправила](https://github.com/htmlacademy-react/132653-what-to-watch-5/pull/5/commits/ac9f8d29b9ef22be0af3c4b4de5c237b0ad9d289)

2020-10-19 20:15 UTC, aalexceenko commented on src/components/add-review-screen/add-review-screen.jsx
> +              <textarea className="add-review__textarea" name="review-text" id="review-text" placeholder="Review text"
[исправила](https://github.com/htmlacademy-react/132653-what-to-watch-5/pull/5/commits/ac9f8d29b9ef22be0af3c4b4de5c237b0ad9d289)

2020-10-20 10:54 UTC, merged